[meshtastic]
connection_type = serial
serial_port = /dev/ttyACM0
baudrate = 115200
network_url = 
verify_ssl = false
bluetooth_mac = 
bluetooth_pin = 
node_id = !12345678

[mqtt]
broker = mozart.uucp
port = 1883
username = 
password = 
keepalive = 60

[daemon]
log_file = /home/njc/dev/meshtastic/meshvm/test_meshvm.log
log_level = INFO
pid_file = /home/njc/dev/meshtastic/meshvm/test_meshvm.pid
history_file = /home/njc/dev/meshtastic/meshvm/test_meshvm_history.md
message_topic = meshvm/send
protobuf_resilience = true

[keywords]
weather = sensors/weather
status = system/status
temp = sensors/temperature
ping = system/ping

